package com.wynnlab.items

class Identifications(
    val healthRegen: OptInt,
    val manaRegen: OptInt,
    val spellDamage: OptInt,
    val damageBonus: OptInt,
    val lifeSteal: OptInt,
    val manaSteal: OptInt,
    val xpBonus: OptInt,
    val lootBonus: OptInt,
    val reflection: OptInt,
    val strengthPoints: OptInt,
    val dexterityPoints: OptInt,
    val intelligencePoints: OptInt,
    val defensePoints: OptInt,
    val agilityPoints: OptInt,
    val thorns: OptInt,
    val exploding: OptInt,
    val speed: OptInt,
    val attackSpeedBonus: OptInt,
    val poison: OptInt,
    val healthBonus: OptInt,
    val soulPoints: OptInt,
    val emeraldStealing: OptInt,
    val healthRegenRaw: OptInt,
    val spellDamageRaw: OptInt,
    val damageBonusRaw: OptInt,
    val bonusEarthDamage: OptInt,
    val bonusThunderDamage: OptInt,
    val bonusWaterDamage: OptInt,
    val bonusFireDamage: OptInt,
    val bonusAirDamage: OptInt,
    val bonusEarthDefense: OptInt,
    val bonusThunderDefense: OptInt,
    val bonusWaterDefense: OptInt,
    val bonusFireDefense: OptInt,
    val bonusAirDefense: OptInt
)